const fs = require('fs');
const db = require('../source/meme/memes.json');
const del = ['绝区零','宫崎骏','塞尔达传说','海绵宝宝','千与千寻','黑神话悟空','周星驰','妙蛙种子'];
const keep = ['奥利给','栓Q','上头','开盒','渣男','好人卡','真香定律','圈粉','意难平'];
let s = '=== 拟删(纯泛夸,无固定用法) ===\n';
del.forEach(n=>{ const e=db.entries.find(x=>x.name===n); if(e&&e.usage) s += ' - '+n+' :: '+e.usage+'\n'; });
s += '\n=== 保留(有真实用法) ===\n';
keep.forEach(n=>{ const e=db.entries.find(x=>x.name===n); if(e&&e.usage) s += ' - '+n+' :: '+e.usage+'\n'; });
fs.writeFileSync(process.env.TEMP + '\\preview.txt', s, 'utf8');
console.log('written');
